name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential
    
    - name: Clean previous builds
      run: |
        rm -rf _builds builds build
    
    - name: Configure CMake
      run: cmake -H. -Bbuild -DBUILD_TESTS=ON
    
    - name: Build
      run: cmake --build build
    
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
