name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false  # Отключаем синхронизацию submodules
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential
    
    - name: Configure CMake
      run: cmake -H. -B_builds -DBUILD_TESTS=ON
    
    - name: Build
      run: cmake --build _builds
    
    - name: Run tests
      run: |
        cd _builds
        ctest --output-on-failure
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
